/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculatornb8jdk8;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Westy
 * @version 1.2
 * JDK-17
 */
public class frmCalculator extends javax.swing.JFrame {

    private String strInput = "";
    private final String[] strOperators = {"/","x","_","_"};

    private double Calculated = 0;

    /**
     * Creates new form frmCalculator
     */
    public frmCalculator() {
        initComponents();

        setResizable(false);
        setTitle("Calculator");
        this.btnarrOperatorButtons = new JButton[]{btnDevide, btnMulti, btnAdd, btnSubtr};
        this.btnarrNumbersButtons = new JButton[]{btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btn0};
        asignNumberButtonListeners();
        asignOperatorButtonListeners();
    }

    private JButton[] btnarrOperatorButtons;
    private JButton[] btnarrNumbersButtons;

    private void asignNumberButtonListeners() {
        for (JButton Button : btnarrNumbersButtons) {
            Button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    strInput += Button.getText();
                    updateMainlabel(strInput);
                }
            });
        }
    }

    private void asignOperatorButtonListeners() {
        for (JButton Button : btnarrOperatorButtons) {
            Button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    strInput += " " + Button.getText() + " ";
                    updateMainlabel(strInput);
                }
            });
        }
    }
    private String stripWhitespaces(String var){
        return var.replaceAll("\\s", "");
    }


    /**
     * Returns a string format of double (i) stripped-off of it's decimal points if
     * its not a decimal or just a string format if it's decimal.
     * */
    private String trimOutput(double i){
        if(i%1==0){
            return String.valueOf((int)i);
        }else{
            return String.valueOf(i);
        }
    }

    private void updateMainlabel(String out) {
        lblMainOutput.setText(stripWhitespaces(out));
    }

    /**
     * Called after a successfull calculation of user input,
     * displays out to the screen
     * */
    private void updatePassedLabel(String out){
        strInput = "";
        lblPassed.setText(stripWhitespaces(out));
    }
    
    private void showErrMessage(){
        strInput = "";
        updateMainlabel("Syntax Error");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMainOutput = new javax.swing.JLabel();
        lblPassed = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDevide = new javax.swing.JButton();
        btnAddToMemory = new javax.swing.JButton();
        btnRemoveFromMemory = new javax.swing.JButton();
        btnRetriveFromMemory = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnSubtr = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 52, 65));

        lblMainOutput.setBackground(new java.awt.Color(36, 52, 65));
        lblMainOutput.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMainOutput.setForeground(new java.awt.Color(255, 255, 255));
        lblMainOutput.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMainOutput.setText("0");

        lblPassed.setBackground(new java.awt.Color(36, 52, 65));
        lblPassed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassed.setForeground(new java.awt.Color(255, 255, 255));
        lblPassed.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassed.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(36, 52, 65));

        btnDevide.setBackground(new java.awt.Color(36, 52, 65));
        btnDevide.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnDevide.setForeground(new java.awt.Color(237, 128, 46));
        btnDevide.setText("/");
        btnDevide.setBorder(null);
        btnDevide.setFocusable(false);

        btnAddToMemory.setBackground(new java.awt.Color(36, 52, 65));
        btnAddToMemory.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnAddToMemory.setForeground(new java.awt.Color(237, 128, 46));
        btnAddToMemory.setText("M+");
        btnAddToMemory.setBorder(null);
        btnAddToMemory.setFocusable(false);
        btnAddToMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToMemoryActionPerformed(evt);
            }
        });

        btnRemoveFromMemory.setBackground(new java.awt.Color(36, 52, 65));
        btnRemoveFromMemory.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnRemoveFromMemory.setForeground(new java.awt.Color(237, 128, 46));
        btnRemoveFromMemory.setText("M-");
        btnRemoveFromMemory.setBorder(null);
        btnRemoveFromMemory.setFocusable(false);
        btnRemoveFromMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFromMemoryActionPerformed(evt);
            }
        });

        btnRetriveFromMemory.setBackground(new java.awt.Color(36, 52, 65));
        btnRetriveFromMemory.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnRetriveFromMemory.setForeground(new java.awt.Color(237, 128, 46));
        btnRetriveFromMemory.setText("MR");
        btnRetriveFromMemory.setBorder(null);
        btnRetriveFromMemory.setFocusable(false);
        btnRetriveFromMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetriveFromMemoryActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(36, 52, 65));
        btn7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn7.setForeground(new java.awt.Color(203, 203, 203));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setFocusable(false);

        btn8.setBackground(new java.awt.Color(36, 52, 65));
        btn8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn8.setForeground(new java.awt.Color(203, 203, 203));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setFocusable(false);

        btn9.setBackground(new java.awt.Color(36, 52, 65));
        btn9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn9.setForeground(new java.awt.Color(203, 203, 203));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setFocusable(false);

        btnMulti.setBackground(new java.awt.Color(36, 52, 65));
        btnMulti.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(237, 128, 46));
        btnMulti.setText("x");
        btnMulti.setActionCommand("");
        btnMulti.setBorder(null);
        btnMulti.setFocusable(false);

        btnSubtr.setBackground(new java.awt.Color(36, 52, 65));
        btnSubtr.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnSubtr.setForeground(new java.awt.Color(237, 128, 46));
        btnSubtr.setText("-");
        btnSubtr.setBorder(null);
        btnSubtr.setFocusable(false);

        btn6.setBackground(new java.awt.Color(36, 52, 65));
        btn6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn6.setForeground(new java.awt.Color(203, 203, 203));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setFocusable(false);

        btn5.setBackground(new java.awt.Color(36, 52, 65));
        btn5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn5.setForeground(new java.awt.Color(203, 203, 203));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setFocusable(false);

        btn4.setBackground(new java.awt.Color(36, 52, 65));
        btn4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(203, 203, 203));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setFocusable(false);

        btn1.setBackground(new java.awt.Color(36, 52, 65));
        btn1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(203, 203, 203));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setFocusable(false);

        btn2.setBackground(new java.awt.Color(36, 52, 65));
        btn2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(203, 203, 203));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setFocusable(false);

        btn3.setBackground(new java.awt.Color(36, 52, 65));
        btn3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(203, 203, 203));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setFocusable(false);

        btnAdd.setBackground(new java.awt.Color(36, 52, 65));
        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(237, 128, 46));
        btnAdd.setText("+");
        btnAdd.setBorder(null);
        btnAdd.setFocusable(false);

        btnCalculate.setBackground(new java.awt.Color(250, 128, 73));
        btnCalculate.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(203, 203, 203));
        btnCalculate.setText("=");
        btnCalculate.setBorder(null);
        btnCalculate.setFocusable(false);
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(36, 52, 65));
        btnDelete.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Del");
        btnDelete.setBorder(null);
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(36, 52, 65));
        btn0.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        btn0.setForeground(new java.awt.Color(203, 203, 203));
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddToMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveFromMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnRetriveFromMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDevide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSubtr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnAdd, btnAddToMemory, btnDelete, btnDevide, btnMulti, btnRemoveFromMemory, btnRetriveFromMemory, btnSubtr});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnRemoveFromMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetriveFromMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn0, btn1, btn2, btn3, btn4, btn5, btn6, btn7, btn8, btn9, btnAdd, btnAddToMemory, btnCalculate, btnDelete, btnDevide, btnMulti, btnRemoveFromMemory, btnRetriveFromMemory, btnSubtr});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMainOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMainOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private double toDouble(String str){
        return Double.parseDouble(str);
    }
    private boolean calculate(){
        String[] strSplitInput = strInput.split(" ");
        List<String> strList = new ArrayList();
        for(String str: strSplitInput){
            strList.add(str);
        }
        double temp = 0;
        for(String operator: strOperators){
            for(int x=0;x<strList.size();x++){
                try{
                    if(strList.get(x).equals(operator)){
                        switch (operator){
                            case "/":
                                strList.remove(x);
                                x--;
                                temp = toDouble(strList.remove(x))/ toDouble(strList.get(x));
                                break;
                            case "x":
                                strList.remove(x);
                                x--;
                                temp = toDouble(strList.remove(x))* toDouble(strList.get(x));
                                break;

                        }
                        strList.set(x,String.valueOf(temp));
                    }else if(operator.equals("_") && (strList.get(x).equals("+")||strList.get(x).equals("-"))){
                        switch (strList.get(x)){
                            case "+":
                                strList.remove(x);
                                x--;
                                temp = toDouble(strList.remove(x))+ toDouble(strList.get(x));
                                break;
                            case "-":
                                strList.remove(x);
                                x--;
                                temp = toDouble(strList.remove(x))- toDouble(strList.get(x));
                                break;
                        }
                        strList.set(x,String.valueOf(temp));
                    }
                }catch(IndexOutOfBoundsException Ex){
                    System.out.println("IndexOutOfBoundErr: " + Ex.getLocalizedMessage());
                    return false;
                }catch (NumberFormatException Ex){
                    System.out.println("NumberFormatErr: " + Ex.getLocalizedMessage());
                    return false;
                }
            }
        }
        this.Calculated = Math.round(temp*100.0)/100.0;
        return true;
    }

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if(calculate()){
            updateMainlabel(trimOutput(this.Calculated));
            updatePassedLabel(strInput);
        }else{
            showErrMessage();
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (strInput.length() > 0) {
            if (strInput.charAt(strInput.length() - 1) == ' ') {
                strInput = strInput.substring(0, strInput.length() - 3);
            } else {
                strInput = strInput.substring(0, strInput.length() - 1);
            }
        }
        updateMainlabel(strInput);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddToMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToMemoryActionPerformed
        // TODO add your handling code here:
        FileManager.writeToFile(String.valueOf(Calculated));

    }//GEN-LAST:event_btnAddToMemoryActionPerformed

    private void btnRemoveFromMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFromMemoryActionPerformed
        // TODO add your handling code here:
        FileManager.clearFile();
    }//GEN-LAST:event_btnRemoveFromMemoryActionPerformed

    private void btnRetriveFromMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetriveFromMemoryActionPerformed
        // TODO add your handling code here:
        strInput = trimOutput(toDouble(FileManager.retreiveFromFile()));
        updateMainlabel(strInput);
    }//GEN-LAST:event_btnRetriveFromMemoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddToMemory;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDevide;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnRemoveFromMemory;
    private javax.swing.JButton btnRetriveFromMemory;
    private javax.swing.JButton btnSubtr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMainOutput;
    private javax.swing.JLabel lblPassed;
    // End of variables declaration//GEN-END:variables
}
